### ISSUE TITLE
Feature: Tournament organization

### ISSUE THREAD

**Issue by BastianMorawsky** [Rouby/sommerlan#2]
Enables easy tournament organization on the site for every **Verified** user.

- [ ] Create and manage tournaments
- [ ] Create and manage teams
  - specific for a tournament or general?

Tournaments

- [ ] Choose between formats
  - single elimination 
  - double elimination 
  - round robin
  - tables
- [ ] Choose number of participants / teams
- [ ] Choose (allowed) size of teams
- [ ] Enter rewards for 1st, 2nd, 3rd ...
- [ ] Choose the starting date & time
- [ ] Allow creator or teams to input their scores
- [ ] Push notifications for events (start, next round, elimination)

Teams
- [ ] Choose name
- [ ] Choose image
- [ ] Invite other users
- [ ] Allow joining with password

**Comment by Rouby** [comment]
Tournaments should be archivable and later be viewed based on their year.

**Comment by Rouby** [comment]
Tournaments can be documented via Events-feature. Actual tournament pages can be better utilized to organize the actual tournament -> out of scope
