### ISSUE TITLE
Bug: In the blog part of the text comes 2 times.

### ISSUE THREAD

**Issue by BastianMorawsky** [Rouby/sommerlan#9]
Bug: In the blog "Die Sommer-Lan ist vom 01.08 bis 09.08.2020" is displayed 2 times, although it is written just 1 time.

**Comment by Rouby** [comment]
Seems like a bug in the used WYSIWYG editor component. Likely cant handle copy&paste / editing on mobile.

Generally I only test on Chrome, so iPhone / Mobiles not using a native chrome might be buggy 😁 

As a fix, you should be able to edit (your own) news articles and can fix this (hopefully).
